# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Amm\etc\Aimmy2_CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Amm\etc\Aimmy2_CPP\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Amm\etc\Aimmy2_CPP\build\CMakeFiles C:\Amm\etc\Aimmy2_CPP\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Amm\etc\Aimmy2_CPP\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AimmyV2_CPP

# Build rule for target.
AimmyV2_CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AimmyV2_CPP
.PHONY : AimmyV2_CPP

# fast build rule for target.
AimmyV2_CPP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/build
.PHONY : AimmyV2_CPP/fast

#=============================================================================
# Target rules for targets named AimmyV2_CPP_autogen_timestamp_deps

# Build rule for target.
AimmyV2_CPP_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AimmyV2_CPP_autogen_timestamp_deps
.PHONY : AimmyV2_CPP_autogen_timestamp_deps

# fast build rule for target.
AimmyV2_CPP_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP_autogen_timestamp_deps.dir\build.make CMakeFiles/AimmyV2_CPP_autogen_timestamp_deps.dir/build
.PHONY : AimmyV2_CPP_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named AimmyV2_CPP_autogen

# Build rule for target.
AimmyV2_CPP_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AimmyV2_CPP_autogen
.PHONY : AimmyV2_CPP_autogen

# fast build rule for target.
AimmyV2_CPP_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP_autogen.dir\build.make CMakeFiles/AimmyV2_CPP_autogen.dir/build
.PHONY : AimmyV2_CPP_autogen/fast

AimmyV2_CPP_autogen/mocs_compilation.obj: AimmyV2_CPP_autogen/mocs_compilation.cpp.obj
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.obj

# target to build an object file
AimmyV2_CPP_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/AimmyV2_CPP_autogen/mocs_compilation.cpp.obj
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.cpp.obj

AimmyV2_CPP_autogen/mocs_compilation.i: AimmyV2_CPP_autogen/mocs_compilation.cpp.i
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.i

# target to preprocess a source file
AimmyV2_CPP_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/AimmyV2_CPP_autogen/mocs_compilation.cpp.i
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.cpp.i

AimmyV2_CPP_autogen/mocs_compilation.s: AimmyV2_CPP_autogen/mocs_compilation.cpp.s
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.s

# target to generate assembly for a file
AimmyV2_CPP_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/AimmyV2_CPP_autogen/mocs_compilation.cpp.s
.PHONY : AimmyV2_CPP_autogen/mocs_compilation.cpp.s

predictions/LeadTargetPrediction.obj: predictions/LeadTargetPrediction.cpp.obj
.PHONY : predictions/LeadTargetPrediction.obj

# target to build an object file
predictions/LeadTargetPrediction.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/predictions/LeadTargetPrediction.cpp.obj
.PHONY : predictions/LeadTargetPrediction.cpp.obj

predictions/LeadTargetPrediction.i: predictions/LeadTargetPrediction.cpp.i
.PHONY : predictions/LeadTargetPrediction.i

# target to preprocess a source file
predictions/LeadTargetPrediction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/predictions/LeadTargetPrediction.cpp.i
.PHONY : predictions/LeadTargetPrediction.cpp.i

predictions/LeadTargetPrediction.s: predictions/LeadTargetPrediction.cpp.s
.PHONY : predictions/LeadTargetPrediction.s

# target to generate assembly for a file
predictions/LeadTargetPrediction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/predictions/LeadTargetPrediction.cpp.s
.PHONY : predictions/LeadTargetPrediction.cpp.s

src/AIModel.obj: src/AIModel.cpp.obj
.PHONY : src/AIModel.obj

# target to build an object file
src/AIModel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/AIModel.cpp.obj
.PHONY : src/AIModel.cpp.obj

src/AIModel.i: src/AIModel.cpp.i
.PHONY : src/AIModel.i

# target to preprocess a source file
src/AIModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/AIModel.cpp.i
.PHONY : src/AIModel.cpp.i

src/AIModel.s: src/AIModel.cpp.s
.PHONY : src/AIModel.s

# target to generate assembly for a file
src/AIModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/AIModel.cpp.s
.PHONY : src/AIModel.cpp.s

src/Configs.obj: src/Configs.cpp.obj
.PHONY : src/Configs.obj

# target to build an object file
src/Configs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Configs.cpp.obj
.PHONY : src/Configs.cpp.obj

src/Configs.i: src/Configs.cpp.i
.PHONY : src/Configs.i

# target to preprocess a source file
src/Configs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Configs.cpp.i
.PHONY : src/Configs.cpp.i

src/Configs.s: src/Configs.cpp.s
.PHONY : src/Configs.s

# target to generate assembly for a file
src/Configs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Configs.cpp.s
.PHONY : src/Configs.cpp.s

src/Fonts.obj: src/Fonts.cpp.obj
.PHONY : src/Fonts.obj

# target to build an object file
src/Fonts.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Fonts.cpp.obj
.PHONY : src/Fonts.cpp.obj

src/Fonts.i: src/Fonts.cpp.i
.PHONY : src/Fonts.i

# target to preprocess a source file
src/Fonts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Fonts.cpp.i
.PHONY : src/Fonts.cpp.i

src/Fonts.s: src/Fonts.cpp.s
.PHONY : src/Fonts.s

# target to generate assembly for a file
src/Fonts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Fonts.cpp.s
.PHONY : src/Fonts.cpp.s

src/InputBindingManager.obj: src/InputBindingManager.cpp.obj
.PHONY : src/InputBindingManager.obj

# target to build an object file
src/InputBindingManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/InputBindingManager.cpp.obj
.PHONY : src/InputBindingManager.cpp.obj

src/InputBindingManager.i: src/InputBindingManager.cpp.i
.PHONY : src/InputBindingManager.i

# target to preprocess a source file
src/InputBindingManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/InputBindingManager.cpp.i
.PHONY : src/InputBindingManager.cpp.i

src/InputBindingManager.s: src/InputBindingManager.cpp.s
.PHONY : src/InputBindingManager.s

# target to generate assembly for a file
src/InputBindingManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/InputBindingManager.cpp.s
.PHONY : src/InputBindingManager.cpp.s

src/KeybindEventFilter.obj: src/KeybindEventFilter.cpp.obj
.PHONY : src/KeybindEventFilter.obj

# target to build an object file
src/KeybindEventFilter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/KeybindEventFilter.cpp.obj
.PHONY : src/KeybindEventFilter.cpp.obj

src/KeybindEventFilter.i: src/KeybindEventFilter.cpp.i
.PHONY : src/KeybindEventFilter.i

# target to preprocess a source file
src/KeybindEventFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/KeybindEventFilter.cpp.i
.PHONY : src/KeybindEventFilter.cpp.i

src/KeybindEventFilter.s: src/KeybindEventFilter.cpp.s
.PHONY : src/KeybindEventFilter.s

# target to generate assembly for a file
src/KeybindEventFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/KeybindEventFilter.cpp.s
.PHONY : src/KeybindEventFilter.cpp.s

src/MainWindow.obj: src/MainWindow.cpp.obj
.PHONY : src/MainWindow.obj

# target to build an object file
src/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/MainWindow.cpp.obj
.PHONY : src/MainWindow.cpp.obj

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/OverlayWindow.obj: src/OverlayWindow.cpp.obj
.PHONY : src/OverlayWindow.obj

# target to build an object file
src/OverlayWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/OverlayWindow.cpp.obj
.PHONY : src/OverlayWindow.cpp.obj

src/OverlayWindow.i: src/OverlayWindow.cpp.i
.PHONY : src/OverlayWindow.i

# target to preprocess a source file
src/OverlayWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/OverlayWindow.cpp.i
.PHONY : src/OverlayWindow.cpp.i

src/OverlayWindow.s: src/OverlayWindow.cpp.s
.PHONY : src/OverlayWindow.s

# target to generate assembly for a file
src/OverlayWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/OverlayWindow.cpp.s
.PHONY : src/OverlayWindow.cpp.s

src/PredictAheadTarget.obj: src/PredictAheadTarget.cpp.obj
.PHONY : src/PredictAheadTarget.obj

# target to build an object file
src/PredictAheadTarget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictAheadTarget.cpp.obj
.PHONY : src/PredictAheadTarget.cpp.obj

src/PredictAheadTarget.i: src/PredictAheadTarget.cpp.i
.PHONY : src/PredictAheadTarget.i

# target to preprocess a source file
src/PredictAheadTarget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictAheadTarget.cpp.i
.PHONY : src/PredictAheadTarget.cpp.i

src/PredictAheadTarget.s: src/PredictAheadTarget.cpp.s
.PHONY : src/PredictAheadTarget.s

# target to generate assembly for a file
src/PredictAheadTarget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictAheadTarget.cpp.s
.PHONY : src/PredictAheadTarget.cpp.s

src/PredictionManager.obj: src/PredictionManager.cpp.obj
.PHONY : src/PredictionManager.obj

# target to build an object file
src/PredictionManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictionManager.cpp.obj
.PHONY : src/PredictionManager.cpp.obj

src/PredictionManager.i: src/PredictionManager.cpp.i
.PHONY : src/PredictionManager.i

# target to preprocess a source file
src/PredictionManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictionManager.cpp.i
.PHONY : src/PredictionManager.cpp.i

src/PredictionManager.s: src/PredictionManager.cpp.s
.PHONY : src/PredictionManager.s

# target to generate assembly for a file
src/PredictionManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/PredictionManager.cpp.s
.PHONY : src/PredictionManager.cpp.s

src/RequirementsManager.obj: src/RequirementsManager.cpp.obj
.PHONY : src/RequirementsManager.obj

# target to build an object file
src/RequirementsManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/RequirementsManager.cpp.obj
.PHONY : src/RequirementsManager.cpp.obj

src/RequirementsManager.i: src/RequirementsManager.cpp.i
.PHONY : src/RequirementsManager.i

# target to preprocess a source file
src/RequirementsManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/RequirementsManager.cpp.i
.PHONY : src/RequirementsManager.cpp.i

src/RequirementsManager.s: src/RequirementsManager.cpp.s
.PHONY : src/RequirementsManager.s

# target to generate assembly for a file
src/RequirementsManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/RequirementsManager.cpp.s
.PHONY : src/RequirementsManager.cpp.s

src/SecondaryWindow.obj: src/SecondaryWindow.cpp.obj
.PHONY : src/SecondaryWindow.obj

# target to build an object file
src/SecondaryWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/SecondaryWindow.cpp.obj
.PHONY : src/SecondaryWindow.cpp.obj

src/SecondaryWindow.i: src/SecondaryWindow.cpp.i
.PHONY : src/SecondaryWindow.i

# target to preprocess a source file
src/SecondaryWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/SecondaryWindow.cpp.i
.PHONY : src/SecondaryWindow.cpp.i

src/SecondaryWindow.s: src/SecondaryWindow.cpp.s
.PHONY : src/SecondaryWindow.s

# target to generate assembly for a file
src/SecondaryWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/SecondaryWindow.cpp.s
.PHONY : src/SecondaryWindow.cpp.s

src/Settings.obj: src/Settings.cpp.obj
.PHONY : src/Settings.obj

# target to build an object file
src/Settings.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Settings.cpp.obj
.PHONY : src/Settings.cpp.obj

src/Settings.i: src/Settings.cpp.i
.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s
.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/UserController.obj: src/UserController.cpp.obj
.PHONY : src/UserController.obj

# target to build an object file
src/UserController.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/UserController.cpp.obj
.PHONY : src/UserController.cpp.obj

src/UserController.i: src/UserController.cpp.i
.PHONY : src/UserController.i

# target to preprocess a source file
src/UserController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/UserController.cpp.i
.PHONY : src/UserController.cpp.i

src/UserController.s: src/UserController.cpp.s
.PHONY : src/UserController.s

# target to generate assembly for a file
src/UserController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/UserController.cpp.s
.PHONY : src/UserController.cpp.s

src/Visualization.obj: src/Visualization.cpp.obj
.PHONY : src/Visualization.obj

# target to build an object file
src/Visualization.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Visualization.cpp.obj
.PHONY : src/Visualization.cpp.obj

src/Visualization.i: src/Visualization.cpp.i
.PHONY : src/Visualization.i

# target to preprocess a source file
src/Visualization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Visualization.cpp.i
.PHONY : src/Visualization.cpp.i

src/Visualization.s: src/Visualization.cpp.s
.PHONY : src/Visualization.s

# target to generate assembly for a file
src/Visualization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/Visualization.cpp.s
.PHONY : src/Visualization.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AimmyV2_CPP.dir\build.make CMakeFiles/AimmyV2_CPP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... AimmyV2_CPP_autogen
	@echo ... AimmyV2_CPP_autogen_timestamp_deps
	@echo ... AimmyV2_CPP
	@echo ... AimmyV2_CPP_autogen/mocs_compilation.obj
	@echo ... AimmyV2_CPP_autogen/mocs_compilation.i
	@echo ... AimmyV2_CPP_autogen/mocs_compilation.s
	@echo ... predictions/LeadTargetPrediction.obj
	@echo ... predictions/LeadTargetPrediction.i
	@echo ... predictions/LeadTargetPrediction.s
	@echo ... src/AIModel.obj
	@echo ... src/AIModel.i
	@echo ... src/AIModel.s
	@echo ... src/Configs.obj
	@echo ... src/Configs.i
	@echo ... src/Configs.s
	@echo ... src/Fonts.obj
	@echo ... src/Fonts.i
	@echo ... src/Fonts.s
	@echo ... src/InputBindingManager.obj
	@echo ... src/InputBindingManager.i
	@echo ... src/InputBindingManager.s
	@echo ... src/KeybindEventFilter.obj
	@echo ... src/KeybindEventFilter.i
	@echo ... src/KeybindEventFilter.s
	@echo ... src/MainWindow.obj
	@echo ... src/MainWindow.i
	@echo ... src/MainWindow.s
	@echo ... src/OverlayWindow.obj
	@echo ... src/OverlayWindow.i
	@echo ... src/OverlayWindow.s
	@echo ... src/PredictAheadTarget.obj
	@echo ... src/PredictAheadTarget.i
	@echo ... src/PredictAheadTarget.s
	@echo ... src/PredictionManager.obj
	@echo ... src/PredictionManager.i
	@echo ... src/PredictionManager.s
	@echo ... src/RequirementsManager.obj
	@echo ... src/RequirementsManager.i
	@echo ... src/RequirementsManager.s
	@echo ... src/SecondaryWindow.obj
	@echo ... src/SecondaryWindow.i
	@echo ... src/SecondaryWindow.s
	@echo ... src/Settings.obj
	@echo ... src/Settings.i
	@echo ... src/Settings.s
	@echo ... src/UserController.obj
	@echo ... src/UserController.i
	@echo ... src/UserController.s
	@echo ... src/Visualization.obj
	@echo ... src/Visualization.i
	@echo ... src/Visualization.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

